### ISSUE TITLE
Failed to compile YCM

### ISSUE THREAD

**Issue by Bunchhieng** [VundleVim/Vundle.vim#702]
Please help. I can't seem to compile YCM. 
```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
ycm/CMakeFiles/ycm_core.dir/build.make:514: recipe for target 'ycm/CMakeFiles/ycm_core.dir/ycm_core.cpp.o' failed
make[3]: *** [ycm/CMakeFiles/ycm_core.dir/ycm_core.cpp.o] Error 4
CMakeFiles/Makefile2:127: recipe for target 'ycm/CMakeFiles/ycm_core.dir/all' failed
make[2]: *** [ycm/CMakeFiles/ycm_core.dir/all] Error 2
CMakeFiles/Makefile2:139: recipe for target 'ycm/CMakeFiles/ycm_core.dir/rule' failed
make[1]: *** [ycm/CMakeFiles/ycm_core.dir/rule] Error 2
Makefile:122: recipe for target 'ycm_core' failed
make: *** [ycm_core] Error 2
Traceback (most recent call last):
  File "/home/bun/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 445, in <module>
    Main()
  File "/home/bun/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 434, in Main
    BuildYcmdLib( args )
  File "/home/bun/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 342, in BuildYcmdLib
    subprocess.check_call( build_command )
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'ycm_core', '--', '-j', '1']' returned non-zero exit status 2
Traceback (most recent call last):
  File "./install.py", line 32, in <module>
    Main()
  File "./install.py", line 21, in Main
    subprocess.check_call( [ python_binary, build_file ] + sys.argv[1:] )
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/bun/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py', '--all']' returned non-zero exit status 1

```

**Comment by Bunchhieng** [comment]
Oops wrong repo.
